version: '3.8'

services:
  mariadb:
    image: "mariadb:latest"
    restart: 'always'
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "heticdb"
      MYSQL_USER: "hetic"
      MYSQL_PASSWORD: "hetic"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: "phpmyadmin"
    restart: always
    depends_on:
      - mariadb
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

  wordpress:
    image: "wordpress:latest"
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: heticdb
      WORDPRESS_DB_USER: hetic
      WORDPRESS_DB_PASSWORD: hetic
    volumes:
      - "./wordpress:/var/www/html"